name: citatoios
description: "Your AI-powered reading companion that transforms newsletter overload into organized, actionable insights."
publish_to: 'none'
version: 0.1.2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.2 
  flutter_dotenv: ^5.1.0
  tiktoklikescroller: ^0.2.8
  logger: ^2.5.0
  webview_flutter: ^4.10.0
  flutter_markdown: ^0.7.6+2
  flutter_speed_dial: ^7.0.0
  google_sign_in: ^6.2.2
  app_links: ^6.3.3
  url_launcher: ^6.3.1
  flutter_signin_button: ^2.0.0
  timeago: ^3.7.0
  flutter_widget_from_html: ^0.16.0
  firebase_core: ^2.24.2
  firebase_analytics: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
