// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzCdyQ_WaYyUzCOejy3n9ATBjB154m6Qo',
    appId: '1:287281124301:web:6269614fa7523e850a2a84',
    messagingSenderId: '287281124301',
    projectId: 'citato-ai---ios',
    authDomain: 'citato-ai---ios.firebaseapp.com',
    storageBucket: 'citato-ai---ios.firebasestorage.app',
    measurementId: 'G-7S0QF32977',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFZ4TXanCinCxBOLxkFgEjELkYgj6xUhI',
    appId: '1:287281124301:android:04a8d0111612386c0a2a84',
    messagingSenderId: '287281124301',
    projectId: 'citato-ai---ios',
    storageBucket: 'citato-ai---ios.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0FYdAJsDNhtJecYR2p2hY2fKLskGVkig',
    appId: '1:287281124301:ios:9784b330db4daf3e0a2a84',
    messagingSenderId: '287281124301',
    projectId: 'citato-ai---ios',
    storageBucket: 'citato-ai---ios.firebasestorage.app',
    iosBundleId: 'com.example.citatoios',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0FYdAJsDNhtJecYR2p2hY2fKLskGVkig',
    appId: '1:287281124301:ios:9784b330db4daf3e0a2a84',
    messagingSenderId: '287281124301',
    projectId: 'citato-ai---ios',
    storageBucket: 'citato-ai---ios.firebasestorage.app',
    iosBundleId: 'com.example.citatoios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzCdyQ_WaYyUzCOejy3n9ATBjB154m6Qo',
    appId: '1:287281124301:web:a7d78689d275edc50a2a84',
    messagingSenderId: '287281124301',
    projectId: 'citato-ai---ios',
    authDomain: 'citato-ai---ios.firebaseapp.com',
    storageBucket: 'citato-ai---ios.firebasestorage.app',
    measurementId: 'G-DBPJVB2VNH',
  );
}
